### ISSUE TITLE
my local storage name got the pre fix

### ISSUE THREAD

**Issue by applemate** [pamelafox/lscache#104]
![CleanShot 2024-09-11 at 16 14 01](https://github.com/user-attachments/assets/59c9fe1f-7647-4fda-a307-46291834e2bb)

What can I do to get rid of the prefix ` lscached- ` ?

**Comment by pamelafox** [comment]
You can bring in the JavaScript yourself and change this line here:
https://github.com/pamelafox/lscache/blob/a472e298200da00b9832260d1a9244a1f6dd3c68/lscache.js#L35

We don't have plans to change that in the installable package, but you're welcome to copy the JS code yourself!
