### ISSUE TITLE
Completely full lscache will error and make it seem like it is unsupported.

### ISSUE THREAD

**Issue by jcarlsonLO** [pamelafox/lscache#32]
In the case where you do something horrible like fill up local storage, you can perfectly fill the cache so the support check will fail.   Once the support check fails, you can no longer use flush or any of the expires method.    

This just adds a check on the error / test so that if the problem is we filled up local storage then we definitely have local storage support.    Ran into this on Chrome and FF recently and we could not figure out till recently what was going wrong :).

Code attached since my changes were on dos2unix files.  Maybe the PR will be kind.

<pre>
  function supportsStorage() {
    var key = '__lscachetest__';
    var value = key;

    if (cachedStorage !== undefined) {
      return cachedStorage;
    }

    try {
      setItem(key, value);
      removeItem(key);
      cachedStorage = true;
    } catch (e) {
        if (e.name === 'QUOTA_EXCEEDED_ERR' ||
            e.name === 'NS_ERROR_DOM_QUOTA_REACHED' ||
            e.name === 'QuotaExceededError') {
            cachedStorage = true; //If we hit the limit, then it means we have support, 
                                  //just maxed it out and even the set test failed.
        } else {
            cachedStorage = false;
        }
    }
    return cachedStorage;
  }
</pre>

**Comment by wsanchez** [comment]
Since #33 is merged, should this issue be closed?

**Comment by pamelafox** [comment]
Sure! Thanks for noticing!
