### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by jkrehm** [pamelafox/lscache#39]
Even though bower.json was updated to 1.0.5, when I update my `bower.json` to 1.0.5 and run `bower update`, it doesn't update to 1.0.5 because it doesn't find a tag named 1.0.5.

Could you push a git tag named 1.0.5?

**Comment by jkrehm** [comment]
*Bump* Any word on pushing out a 1.0.5 tag?

**Comment by pamelafox** [comment]
Ahh, oops, git push didn't send the tag.

I apologize for being so bad at maintaining this library, I don't use it for work or any side projects, so it's easy to let fall by the wayside. If someone else was actively using it and wanted to maintain it, let me know.

Anyway, I've git push'd the tag now.
