### ISSUE TITLE
Do a release

### ISSUE THREAD

**Issue by stevejhiggs** [pamelafox/lscache#56]
The last published version of this package is from Nov 2014. It would be great to get a new release up :)

**Comment by pamelafox** [comment]
Do you mean an npm release? I'll admit I'm dusty when it comes to the world of npm, and I don't have a full-time laptop these days. (I'm more of an artist than a coder at the moment). If you could remind me the steps to do a release, then I can do it when I've got some laptop time. Thanks!

**Comment by stevejhiggs** [comment]
no problem.

steps to publish:

increase the package version number in package.json

on the command line in the root dir of the project:

`npm login` - enter your npm username and password
`npm publish`


np

**Comment by pamelafox** [comment]
right-o, I've done that! hope it doesn't bring down the world!

(if anyone watching this ever wants to take over this repo, let me know! i feel funny maintaining a library that i don't actively use. especially when i don't actively code. :D )

**Comment by stevejhiggs** [comment]
happy to help out
