### ISSUE TITLE
Check for local storage throws error in some browsers

### ISSUE THREAD

**Issue by skysteve** [pamelafox/lscache#58]
If a user/browser has disabled access to local storage and throws an error, this error is uncaught. The check should probably be inside a try/catch 

Noticed this in the [brave browser](https://brave.com)

(note this is minified code expanded in dev tools)

<img width="1145" alt="screen shot 2016-07-05 at 14 02 02" src="https://cloud.githubusercontent.com/assets/2196840/16585502/1d62a9c0-42b9-11e6-813d-ca6fead9afb3.png">

**Comment by skysteve** [comment]
Could you please bump the version number and publish an update to npm?

Cheers
Steve

**Comment by pamelafox** [comment]
Sorry for delay, I didn't have any coding setup on this computer yet. 

I've now run the grunt bump task to up the version number and run npm publish to update it on npm, it's at version 1.0.7.

**Comment by skysteve** [comment]
Great thanks :)

**Comment by peter-gribanov** [comment]
Perhaps this issue should be closed?
