### ISSUE TITLE
Unexpected type coercion

### ISSUE THREAD

**Issue by timvanoostrom** [pamelafox/lscache#68]
On line: https://github.com/pamelafox/lscache/blob/master/lscache.js#L211 there is a string check which prevents any string value from being stringified by JSON when setting a value:

```
var a = '1'; // typeof a === 'string';
lsCache.set('a', a);
var b = lsCache.get('a'); // typeof b === 'number'
```

I think removing this line and correctly stringify the JSON value will solve the issue. Try this in your JS console:

```
JSON.parse('"a"') === 'a'
```

**Comment by pamelafox** [comment]
Fixed thanks to you! I'm doing a new tagged release on github/npm now.
