### ISSUE TITLE
localStorage false positive in Chrome with LS disabled

### ISSUE THREAD

**Issue by realdeprez** [pamelafox/lscache#7]
latest Chrome (12.0.742.68 beta) returns !!localStorage.getItem as true even when it's disabled, leads to Error: QUOTA_EXCEEDED_ERR: DOM Exception 22 being thrown when .set() is used

**Comment by peter-gribanov** [comment]
Is it still actual?

**Comment by pamelafox** [comment]
Hm. Don't know, 6 years ago! Seems unlikely. Can close for now, someone can reopen if they see again.
