### ISSUE TITLE
Feature request. Session storage

### ISSUE THREAD

**Issue by krishollenbeck** [pamelafox/lscache#72]
Not really an issue but more of a request:

Probably doesn't make sense to add session storage for a repo called lscache. But could this repo be forked  ( by either you or myself ) and created to also support session storage? (sschace).

**Comment by pamelafox** [comment]
Hello! I won't have time to implement that, but you are welcome to do so. It probably makes most sense as a fork. I'm happy to link it from the Readme for folks looking for that, if you do implement it.

**Comment by krishollenbeck** [comment]
@pamelafox . Thanks for the response. Okay that sounds good. I will look into this thank you.

**Comment by krishollenbeck** [comment]
Here's the sscache or session-storage-cache urls.

- https://github.com/krishollenbeck/session-storage-cache
- https://www.npmjs.com/package/session-storage-cache

I renamed both the npm registry and github repo. To  session-storage-cache . But kept the API as `sscache`. Unfortunately sscache registry name was already taken. So hopefully that isn't to confusing. If you have any thoughts or opinions on that I am open to suggestion.
