### ISSUE TITLE
Indefinite expiry time?

### ISSUE THREAD

**Issue by kokujin** [pamelafox/lscache#73]
Ist the expiry time then indefinite when I leave out this optional parameter?

**Comment by madnight** [comment]
same question here

**Comment by pamelafox** [comment]
Yes, it appears so. Relevant line of code - 
https://github.com/pamelafox/lscache/blob/master/lscache.js#L274
it removes any time that was set before, so there's no longer an expiry key for it:

I wouldn't use this library if you're going to be mostly using it without time though, as it goes through some amount of overhead for deciding whether to remove keys and such. This library is really geared for an expiry-based usage.

We also don't do a lot of tests around the use case of not specifying a time.
