### ISSUE TITLE
How to renew the expiration time?

### ISSUE THREAD

**Issue by neesonqk** [pamelafox/lscache#75]
Assume I've put a `token` variable into lscache with expiration time to 2 minutes from now, then after 1 minute I'd like to recount the expiration time from current time, it's similar to value rewriting.

But it doesn't seem to work with rewriting of the value.

Any idea?

**Comment by peter-gribanov** [comment]
You can reset value

```js
lscache.remove('greeting');
lscache.set('greeting', 'Hello World!', 2);
```

Or you can hardcore change the expiration time

```js
localStorage.setItem(CACHE_PREFIX + cacheBucket + key + CACHE_SUFFIX, expirationTime);
```

**Comment by pamelafox** [comment]
Thanks for answering! Closing this.
