### ISSUE TITLE
Is there a schedule to support the IndexedDB and web SQL ?

### ISSUE THREAD

**Issue by mangoooooo** [pamelafox/lscache#84]
[localforage](https://github.com/localForage/localForage) could be a good choice.

If lscache support the use of the database, I won't worry about out of space anymore.

**Comment by pamelafox** [comment]
No, there is nothing like that on the roadmap. (There is no roadmap, really! I mostly accept PRs for small fixes and changes, as this is purposefully a rather small library). I encourage you to explore other options on npm, thanks for stopping by!
