### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by gmaliandi** [pamelafox/lscache#85]
Hi! I need to use the "return success from set" feature introduced in [this PR](https://github.com/pamelafox/lscache/pull/76), so I'm currently consuming the library as a Github dependency. Would it be possible to create a new release so I can get the library from npm? Thanks for the great library :)

**Comment by pamelafox** [comment]
Ok, I just fixed up the test, did a grunt bump:minor and an npm publish, so you should be able to bring it in as 1.3.0. Open up an issue if you encounter anything. Cheers!
