### ISSUE TITLE
Feature request, take() and flash()

### ISSUE THREAD

**Issue by K-Ko** [pamelafox/lscache#89]
Hi,

sorry but I have not the environment to test properly, so may be these functions I added could be helpful...

**take(key)**

"take out" a value wraps `get(key)` and `remove(key)`

**flash()**

Used for flash messages.

Collect messages during runtime with `lscache.flash('msg 1')`, `lscache.flash('msg 2')`, `lscache.flash('msg 3', 'msg 4')`

and get them later, e.g. on next page load with `lscache.flash()`

    var flashKey = '__FLASH__';

    // ...
        
        /**
         * Take a value from localStorage, get() + remove()
         * @param {string} key
         */
        take: function(key) {
            if (!supportsStorage()) return;

            var value = this.get(key);
            this.remove(key);
            return value;
        },

        /**
         * Store or get one time messages
         * If no arguments provided, take out all flash messages
         * If argument(s) was provided add to lscache
         */
        flash: function() {
            if (!supportsStorage()) return;

            var args = Array.prototype.slice.call(arguments);
            var msgs = this.get(flashKey) || [];

            // Take out messages for a call without argument(s)
            if (args.length === 0) {
                this.remove(flashKey);
                return msgs;
            }

            // Add
            this.set(flashKey, msgs.concat(args));
        },

**Comment by pamelafox** [comment]
Agreed! Thanks for that response, Peter. I'll close this issue.
