### ISSUE TITLE
storage format string?

### ISSUE THREAD

**Issue by Parcley** [pamelafox/lscache#91]
I have noticed that lscache stores items as strings
(while the native localstorage api stores them in the input type, e.g. object or number)

would it be possible to drop lscache's stringification out?
This would make it easier to debug the localstorage in a browser (with the browser's native object-layouting mechanism)

**Comment by Parcley** [comment]
Thanks @peter-gribanov for referring the localStorage doc and for posting the example. With oyur example it all seems to be ok. 
After changing the example a bit, I came up with another example in which lscache behaves differently than localStorage:

```
const itemToStore = ["a", "b"];

localStorage.setItem('nativeLocalStorage', itemToStore);
let retrievedItemNative = localStorage.getItem('nativeLocalStorage');
console.log("item localStorage: " + retrievedItemNative);
console.log("type localStorage: " + typeof retrievedItemNative);

lscache.set('lscache', itemToStore);
let retrievedItemLscache = lscache.get('lscache');
console.log("item lscache: " + retrievedItemLscache);
console.log("type lscache:" + typeof retrievedItemLscache);
```
(tested by using http://pamelafox.github.io/lscache/demo.html)

also note the chrome 73 debugger view after executing the above code:

![image](https://user-images.githubusercontent.com/713312/55858747-c4ef6980-5b70-11e9-9df6-1b46f3f9f726.png)

**Comment by peter-gribanov** [comment]
Exactly. LocalStorage allows storing only strings. In your example, the array was converted to a string and is not restored back to a array. This behavior corresponds to the specification.

In the lscache, the value is [converted to JSON](https://github.com/pamelafox/lscache/blob/master/lscache.js#L217) and [back](https://github.com/pamelafox/lscache/blob/master/lscache.js#L299), which allows you to save the data type of the value.

```js
const itemToStore = ["a", "b"];

localStorage.setItem('nativeLocalStorage', itemToStore);
let retrievedItemNative = localStorage.getItem('nativeLocalStorage');
console.log("item localStorage: ", retrievedItemNative); // a,b
console.log("type localStorage: ", typeof retrievedItemNative); // string
console.log("value 1 localStorage: ", retrievedItemNative[0] === itemToStore[0]); // true
console.log("value 2 localStorage: ", retrievedItemNative[1] === itemToStore[1]); // false

lscache.set('lscache', itemToStore);
let retrievedItemLscache = lscache.get('lscache');
console.log("item lscache:", retrievedItemLscache); // ["a", "b"]
console.log("type lscache:", typeof retrievedItemLscache); // object
console.log("value 1 lscache:", retrievedItemLscache[0] === itemToStore[0]); // true
console.log("value 2 lscache:", retrievedItemLscache[1] === itemToStore[1]); // true
```

> I have noticed that lscache stores items as strings
(while the native localstorage api stores them in the input type, e.g. object or number)

That is, the situation is exactly the opposite. Both lscache and LocalStorage store data as strings regardless of the data type of the value. But LocalStorage always returns strings, and lscache returns data in the same type in which they were stored.

Sorry, but i do not understand your problem.

**Comment by Parcley** [comment]
sorry for not pointing out the issue clearly.

When I store complex data structures in the localStorage, they are not stringified. This means that I can explre the data structure nicely in a browser developer tools (possibly with clickable tree structure).

If a data structure is converted to a JSON string before being stored in the localStorage, the browser developer tools will only show it as a String (possible with escape characters), which is not as nice to view as a native datatype.

So it is only about being able to view and copy items from the browser localStorage directly (by using chrome developer tools)

**Comment by peter-gribanov** [comment]
> When I store complex data structures in the localStorage, they are not stringified.

Sorry, but i still do not understand you. If you store complex data structures in localStorage, they are converted to strings when saved.

Again. When saved, the data is converted to a string and all information about the data type is lost [(see JavaScript Type Conversion Table)](https://www.w3schools.com/js/js_type_conversion.asp).

```js
localStorage.setItem('nativeLocalStorage', String(itemToStore)); // converted to string
```

Try to store an instance of the SomeButton class:

```js
class SomeButton {
 constructor(name) {
  this.name = name;
 }
 name() {
  return this.name;
 }
}

const itemToStore = new SomeButton('foo');

localStorage.setItem('nativeLocalStorage', itemToStore);
let retrievedItemNative = localStorage.getItem('nativeLocalStorage');
console.log("item localStorage: ", retrievedItemNative); // [object Object]
console.log("type localStorage: ", typeof retrievedItemNative); // string

lscache.set('lscache', itemToStore);
let retrievedItemLscache = lscache.get('lscache');
console.log("item lscache:", retrievedItemLscache); // {name: "foo"}
console.log("type lscache:", typeof retrievedItemLscache); // object
```
![image](https://user-images.githubusercontent.com/1954436/55877324-6e9b1e80-5ba2-11e9-8f14-2c3154d83821.png)
![image](https://user-images.githubusercontent.com/1954436/55877289-56c39a80-5ba2-11e9-8226-996de671bad5.png)

I see that everything is exactly the opposite. Data storage in JSON allows you to view the structure and nesting of data. Navigate the data tree in a browser developer tools. You can freely copy this data directly from the browser and paste wherever you want.

![image](https://user-images.githubusercontent.com/1954436/55878768-c25b3700-5ba5-11e9-8134-487f4c05df38.png)

![image](https://user-images.githubusercontent.com/1954436/55878796-d737ca80-5ba5-11e9-94f4-6014b0a9af64.png)

**Comment by Parcley** [comment]
Hi @peter-gribanov 
I have checked my application and somewhere I was actually already `JSON.stringify`ing my data.
So the issue is in my application. With lscache, I was stringifying twice leading to the described behaviour. 
I was not checking my surrounding application code thorough enough, but was just using lscache as a drop-in replacement for localStorage.
Sorry to have used your precious time and thanks for the detailed feedback
